export default {
    routes: {
        work: '/work',
        ui: '/work/ui',
        graphic: '/work/graphic',
        coding: '/work',
        photos: '/gallery',
        about: '/about',
        contact: '/contact'
    },
    images: {
        profile: './img/linkedin.jpg',
        logo: './img/initials1.svg',
        breez: './img/breez/breez_logo.svg',
        diets: './img/diets.png',
        words: './img/words/words.svg',
        background: './img/background.svg',
        harley: './img/harley/harley.jpg',
        harley_origin: './img/harley/harley_original.jpg',
        kobe: './img/kobe/kobe.svg',
        kobe_origin: './img/kobe/kobe_original.png',
        broad: './img/wushu/broad_sword.jpg',
        broad_origin: './img/wushu/broad_sword_original.jpg',
        straight: './img/wushu/straight_sword.jpg',
        straight_origin: './img/wushu/straight_sword_original.jpg',
        spear: './img/wushu/spear.jpg',
        spear_origin: './img/wushu/spear_original.jpg',
        long: './img/wushu/long_fist.jpg',
        long_origin: './img/wushu/long_fist_original.jpg',
        helmet: './img/bike/helmet.svg',
        helmet_b: './img/bike/helmet_blank.svg',
        helmets: './img/bike/helmets.svg',
        tshirt: './img/bike/tshirt.svg',
        bottle: './img/bike/bottle.png',
        ideation: './img/breez/ideation2.jpg',
        system: './img/breez/systems.png',
        productivity: './img/breez/productivity.png',
        communication_media: './img/breez/combined.png',
        wireframe: './img/breez/wireframes.svg',
        heat_map: './img/breez/heat_map.png',
        gestures: './img/breez/gestures.svg',
        iteration: './img/breez/iteration.png',
        sketch: './img/breez/sketches.png',
        orbiter: './img/breez/orbiter.png'
    }
}